services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kibi
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./apps/api:/usr/src/app
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SERVICE_ROLE_KEY: ${SERVICE_ROLE_KEY}
      MAKE_WEBHOOK_TOKEN: ${MAKE_WEBHOOK_TOKEN}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      RESEND_API_KEY: ${RESEND_API_KEY}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_JWT_SECRET: ${SUPABASE_JWT_SECRET}
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    working_dir: /usr/src/apps/web
    command: pnpm dev
    volumes:
      - ./apps/web:/usr/src/apps/web
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_SUPABASE_URL: ${SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
volumes:
  postgres_data: {}
