// import React from 'react';
// import AuthProvider from '../contexts/AuthContext';
// import '../styles/globals.css';

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body>
//         <AuthProvider>
//           {children}
//         </AuthProvider>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";

//import Nav from "@/components/nav";

import "../app/index.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        {/*<Nav />*/}
        <main className="px-4 py-8">{children}</main>
      </body>
    </html>
  );
}