"""initial schema

Revision ID: c4914cbd2b00
Revises: 
Create Date: 2025-04-23 23:55:07.034569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4914cbd2b00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('workflow', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('time_saved', sa.Float(), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_runs_id'), 'automation_runs', ['id'], unique=False)
    op.create_index(op.f('ix_automation_runs_user_id'), 'automation_runs', ['user_id'], unique=False)
    op.create_table('user_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_credits_id'), 'user_credits', ['id'], unique=False)
    op.create_index(op.f('ix_user_credits_user_id'), 'user_credits', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_credits_user_id'), table_name='user_credits')
    op.drop_index(op.f('ix_user_credits_id'), table_name='user_credits')
    op.drop_table('user_credits')
    op.drop_index(op.f('ix_automation_runs_user_id'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_id'), table_name='automation_runs')
    op.drop_table('automation_runs')
    # ### end Alembic commands ###
